#!/usr/bin/env python3
"""Generate notebooks/05_analysis.ipynb (interactive SAE analysis)."""
import json
from pathlib import Path

NB = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# SAE Interpretability Explorer\n",
                "\n",
                "Interactive analysis + visualization of a trained Sparse Autoencoder on the "
                "frozen MGN node embeddings (per arXiv:2507.16069).\n",
                "\n",
                "Loads an **existing** run (produced by `train_mgn` -> `extract_embeddings` -> "
                "`train_sae`), then lets you:\n",
                "- Rank Top-K salient latents by the three Table-1 scores (Variance, MeanAbs, Entropy).\n",
                "- Inspect any latent's activation histogram.\n",
                "- Visualize a latent's **spatial activation** on the most-activated frame.\n",
                "\n",
                "All plotting goes through `src/visualize.py` (shared with the CLI).",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# --- Setup ---\n",
                "import sys\n",
                "from pathlib import Path\n",
                "\n",
                "REPO_ROOT = Path.cwd()\n",
                "if REPO_ROOT.name == 'notebooks':\n",
                "    REPO_ROOT = REPO_ROOT.parent\n",
                "if str(REPO_ROOT) not in sys.path:\n",
                "    sys.path.insert(0, str(REPO_ROOT))\n",
                "\n",
                "import numpy as np\n",
                "import matplotlib.pyplot as plt\n",
                "plt.rcParams['figure.figsize'] = (7, 4)\n",
                "\n",
                "from src.env import get_env\n",
                "from src.visualize import top_latents_bar, latent_histogram, spatial_scatter\n",
                "from scripts.analyze import load_all_codes, salient_scores\n",
                "from src.data.cylinder_flow import split_reader, build_sample\n",
                "import ipywidgets as widgets\n",
                "from IPython.display import display\n",
                "print('setup OK; repo:', REPO_ROOT)",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# --- Load a run ---\n",
                "# Pick the run_name whose SAE/embeddings you want to explore, and the split.\n",
                "run_name_w = widgets.Text(value='norm-smoke', description='run_name')\n",
                "split_w = widgets.Dropdown(options=['train', 'valid', 'test'], value='test', description='split')\n",
                "display(run_name_w, split_w)\n",
                "\n",
                "env = get_env(hardware='auto', run_name=run_name_w.value, stage='analysis', seed=0)\n",
                "split = split_w.value\n",
                "\n",
                "# Codes (z) for every node-vector, plus the saved normalization stats.\n",
                "codes, _ = load_all_codes(env.embed_dir, split, env.sae_ckpt_dir)\n",
                "M, hidden = codes.shape\n",
                "print(f'split={split}  samples={M}  hidden={hidden}')\n",
                "\n",
                "# Paper Table-1 saliency scores.\n",
                "scores = salient_scores(codes, bins=50)\n",
                "for name, s in scores.items():\n",
                "    print(f'  {name}: max={s.max():.4f}  mean={s.mean():.4f}')\n",
                "\n",
                "TOP_K = 20\n",
                "top = {name: np.argsort(-s)[:TOP_K] for name, s in scores.items()}",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# --- Top-K salient latents (Table 1) ---\n",
                "for metric in ['variance', 'mean_abs', 'entropy']:\n",
                "    fig = top_latents_bar(scores, top[metric], title=f'Top-{TOP_K} by {metric}')\n",
                "    display(fig)",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Interactive latent inspection\n",
                "\n",
                "Slide to choose a latent index. The histogram shows its activation distribution "
                "across all samples; below it, the **most-activated frame** is shown as a spatial "
                "heatmap (node color = that latent's activation).",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# --- Per-latent interactivity ---\n",
                "def frame_positions(data_dir, split, ex, fr):\n",
                "    \"\"\"Return (N,2) mesh positions for one (example, frame).\"\"\"\n",
                "    example = next((e for i, e in enumerate(split_reader(data_dir, split)) if i == ex))\n",
                "    return example['mesh_pos']  # [N, 2]\n",
                "\n",
                "def top_frame_for_latent(latent_idx):\n",
                "    \"\"\"Find the single (example, frame) whose mean activation of `latent_idx` is highest.\"\"\"\n",
                "    # Load the SAE once (reused across files).\n",
                "    import torch\n",
                "    from src.models.sae import SAEConfig, SparseAutoencoder\n",
                "    embed_dim = int(np.load(sorted((env.embed_dir / split).glob('*.npy'))[0]).shape[1])\n",
                "    ck = __import__('src.utils.checkpoint', fromlist=['load_latest']).load_latest(env.sae_ckpt_dir)\n",
                "    sae = SparseAutoencoder(SAEConfig(input_dim=embed_dim))\n",
                "    sae.load_state_dict(ck['model_state'])\n",
                "    sae.eval()\n",
                "    stats = __import__('scripts.analyze', fromlist=['load_normalizer']).load_normalizer(env.embed_dir)\n",
                "    best_ex, best_fr, best_mean = -1, -1, -1.0\n",
                "    for p in sorted((env.embed_dir / split).glob('ex*_fr*.npy')):\n",
                "        stem = p.stem  # ex{ex}_fr{fr}\n",
                "        ex = int(stem.split('_')[0][2:])\n",
                "        fr = int(stem.split('_')[1][2:])\n",
                "        arr = np.load(p).astype('float32')\n",
                "        if stats is not None:\n",
                "            mean, std = stats\n",
                "            arr = (arr - mean) / std\n",
                "        with torch.no_grad():\n",
                "            zc = sae.encode(torch.as_tensor(arr)).numpy()\n",
                "        mean_act = float(zc[:, latent_idx].mean())\n",
                "        if mean_act > best_mean:\n",
                "            best_mean, best_ex, best_fr = mean_act, ex, fr\n",
                "    return best_ex, best_fr\n",
                "\n",
                "latent_slider = widgets.IntSlider(value=0, min=0, max=hidden - 1, step=1, description='latent')\n",
                "display(latent_slider)\n",
                "\n",
                "# Cache the SAE + normalizer so slider moves stay snappy.\n",
                "import torch\n",
                "from src.models.sae import SAEConfig, SparseAutoencoder\n",
                "embed_dim = int(np.load(sorted((env.embed_dir / split).glob('*.npy'))[0]).shape[1])\n",
                "_ck = __import__('src.utils.checkpoint', fromlist=['load_latest']).load_latest(env.sae_ckpt_dir)\n",
                "_sae = SparseAutoencoder(SAEConfig(input_dim=embed_dim)); _sae.load_state_dict(_ck['model_state']); _sae.eval()\n",
                "_stats = __import__('scripts.analyze', fromlist=['load_normalizer']).load_normalizer(env.embed_dir)\n",
                "def _codes_for(arr):\n",
                "    if _stats is not None:\n",
                "        mean, std = _stats; arr = (arr - mean) / std\n",
                "    with torch.no_grad():\n",
                "        return _sae.encode(torch.as_tensor(arr.astype('float32'))).numpy()\n",
                "\n",
                "def inspect(latent_idx):\n",
                "    display(latent_histogram(codes, latent_idx))\n",
                "    ex, fr = top_frame_for_latent(latent_idx)\n",
                "    pos = frame_positions(env.data_dir, split, ex, fr)\n",
                "    p = sorted((env.embed_dir / split).glob(f'ex{ex:05d}_fr{fr:04d}.npy'))[0]\n",
                "    node_act = _codes_for(np.load(p))[:, latent_idx]\n",
                "    fig = spatial_scatter(pos, node_act, title=f'latent {latent_idx}: top frame ex{ex} fr{fr}')\n",
                "    display(fig)\n",
                "    print(f'most-activated frame: ex={ex} fr={fr}  mean activation={node_act.mean():.4f}')\n",
                "\n",
                "out = widgets.interactive_output(inspect, {'latent_idx': latent_slider})",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Render the interactive inspector (slider + plots).\n",
                "display(latent_slider, out)",
            ],
        },
    ],
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.12"},
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

Path("notebooks").mkdir(exist_ok=True)
out = Path("notebooks/05_analysis.ipynb")
out.write_text(json.dumps(NB, indent=1))
print("wrote", out, out.stat().st_size, "bytes")
